name: Publish Docker Image

on:
  push:
    branches: [master]
    paths:
      - "clash.meta/version.txt"
  workflow_dispatch:

env:
  PROJECT_NAME: clash.meta

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
        working-directory: "${{ env.PROJECT_NAME }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v6
            linux/arm/v7
          push: true
          build-args: |
            VERSION=${{ steps.version.outputs.content }}
          tags: |
            yikyo/clash.meta:latest
            yikyo/clash.meta:${{ steps.version.outputs.content }}
        working-directory: "${{ env.PROJECT_NAME }}"
