name: OVERRIDE - Publish Docker Image

on:
  push:
    branches: [master]
    paths:
      - "override/version.txt"
  workflow_dispatch:

env:
  PROJECT_NAME: override

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: "${{ env.PROJECT_NAME }}/version.txt"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ env.PROJECT_NAME }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            VERSION=${{ steps.version.outputs.content }}
          tags: |
            yikyo/override:latest
            yikyo/override:${{ steps.version.outputs.content }}
